version: "3.8"

# Docker Networks
# networks:
#   DC-network-dev:
#     driver: bridge

# Work Flow Service
services:
  ##### BUILD IMAGE APP #####


  ##### DATABASE #####
  postgres:
    image: postgres:13.3-alpine
    container_name: DC_postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data-dev:/var/lib/postgresql/data
    # networks:
    #   - DC-network-dev
    restart: always

  ##### pgAdmin #####
  pgadmin:
    image: dpage/pgadmin4:5.6
    container_name: DC_pgadmin
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 8080:80
    volumes:
      - pgadmin_data-dev:/var/lib/pgAdmin
    # networks:
    #   - DC-network-dev
    restart: always

# Declare Volume Data
volumes:
  postgres_data-dev:
  pgadmin_data-dev:
